### ISSUE TITLE
provide rightHeader menu option in the header

### ISSUE THREAD

**Issue by veeramarni** [BrandonMA/fractal#5]
Like in `react-navigation` needs to have an option for adding the `rightHeader` option.

**Comment by BrandonMA** [comment]
Are you talking about [right header buttons](https://reactnavigation.org/docs/header-buttons/)? This is already possible by using `NativeNavigationBar` and `NativeNavigationBarRightView`

**Comment by BrandonMA** [comment]
Example:
```
<StackScreen
    navBarConfig={
        <NavigationBarConfig title='Fragments' largeTitle>
            <NativeNavigationBarRightView>{/* Here goes your code */}</NativeNavigationBarRightView>
        </NavigationBarConfig>
    }
    isRootRoute
    path={routes.components}
>
```
